// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package lobby_handler

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CreateRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CreateRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "name"
	err = en.Append(0x81, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CreateRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "name"
	o = append(o, 0x81, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CreateRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CreateRequest) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CreateResponse) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "lobbyId":
			z.LobbyId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "LobbyId")
				return
			}
		case "lobbyToken":
			z.LobbyToken, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "LobbyToken")
				return
			}
		case "playerId":
			z.PlayerId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PlayerId")
				return
			}
		case "playerToken":
			z.PlayerToken, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PlayerToken")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CreateResponse) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "lobbyId"
	err = en.Append(0x84, 0xa7, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.LobbyId)
	if err != nil {
		err = msgp.WrapError(err, "LobbyId")
		return
	}
	// write "lobbyToken"
	err = en.Append(0xaa, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.LobbyToken)
	if err != nil {
		err = msgp.WrapError(err, "LobbyToken")
		return
	}
	// write "playerId"
	err = en.Append(0xa8, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.PlayerId)
	if err != nil {
		err = msgp.WrapError(err, "PlayerId")
		return
	}
	// write "playerToken"
	err = en.Append(0xab, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.PlayerToken)
	if err != nil {
		err = msgp.WrapError(err, "PlayerToken")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CreateResponse) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "lobbyId"
	o = append(o, 0x84, 0xa7, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64)
	o = msgp.AppendString(o, z.LobbyId)
	// string "lobbyToken"
	o = append(o, 0xaa, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e)
	o = msgp.AppendString(o, z.LobbyToken)
	// string "playerId"
	o = append(o, 0xa8, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64)
	o = msgp.AppendString(o, z.PlayerId)
	// string "playerToken"
	o = append(o, 0xab, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e)
	o = msgp.AppendString(o, z.PlayerToken)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CreateResponse) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "lobbyId":
			z.LobbyId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LobbyId")
				return
			}
		case "lobbyToken":
			z.LobbyToken, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LobbyToken")
				return
			}
		case "playerId":
			z.PlayerId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PlayerId")
				return
			}
		case "playerToken":
			z.PlayerToken, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PlayerToken")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CreateResponse) Msgsize() (s int) {
	s = 1 + 8 + msgp.StringPrefixSize + len(z.LobbyId) + 11 + msgp.StringPrefixSize + len(z.LobbyToken) + 9 + msgp.StringPrefixSize + len(z.PlayerId) + 12 + msgp.StringPrefixSize + len(z.PlayerToken)
	return
}
