// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package lobby_handler

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ReadyRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ready":
			z.Ready, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Ready")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ReadyRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "ready"
	err = en.Append(0x81, 0xa5, 0x72, 0x65, 0x61, 0x64, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Ready)
	if err != nil {
		err = msgp.WrapError(err, "Ready")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ReadyRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "ready"
	o = append(o, 0x81, 0xa5, 0x72, 0x65, 0x61, 0x64, 0x79)
	o = msgp.AppendBool(o, z.Ready)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ReadyRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ready":
			z.Ready, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ready")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ReadyRequest) Msgsize() (s int) {
	s = 1 + 6 + msgp.BoolSize
	return
}
