// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package lobby

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *GameStart) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z GameStart) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 0
	_ = z
	err = en.Append(0x80)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z GameStart) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 0
	_ = z
	o = append(o, 0x80)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GameStart) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z GameStart) Msgsize() (s int) {
	s = 1
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PlayerInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "players":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Players")
				return
			}
			if cap(z.Players) >= int(zb0002) {
				z.Players = (z.Players)[:zb0002]
			} else {
				z.Players = make([]PlayerInfoPlayer, zb0002)
			}
			for za0001 := range z.Players {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Players", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Players", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "playerId":
						z.Players[za0001].Id, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Players", za0001, "Id")
							return
						}
					case "name":
						z.Players[za0001].Name, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Players", za0001, "Name")
							return
						}
					case "ready":
						z.Players[za0001].Ready, err = dc.ReadBool()
						if err != nil {
							err = msgp.WrapError(err, "Players", za0001, "Ready")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Players", za0001)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PlayerInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "players"
	err = en.Append(0x81, 0xa7, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Players)))
	if err != nil {
		err = msgp.WrapError(err, "Players")
		return
	}
	for za0001 := range z.Players {
		// map header, size 3
		// write "playerId"
		err = en.Append(0x83, 0xa8, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.Players[za0001].Id)
		if err != nil {
			err = msgp.WrapError(err, "Players", za0001, "Id")
			return
		}
		// write "name"
		err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.Players[za0001].Name)
		if err != nil {
			err = msgp.WrapError(err, "Players", za0001, "Name")
			return
		}
		// write "ready"
		err = en.Append(0xa5, 0x72, 0x65, 0x61, 0x64, 0x79)
		if err != nil {
			return
		}
		err = en.WriteBool(z.Players[za0001].Ready)
		if err != nil {
			err = msgp.WrapError(err, "Players", za0001, "Ready")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PlayerInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "players"
	o = append(o, 0x81, 0xa7, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Players)))
	for za0001 := range z.Players {
		// map header, size 3
		// string "playerId"
		o = append(o, 0x83, 0xa8, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64)
		o = msgp.AppendString(o, z.Players[za0001].Id)
		// string "name"
		o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
		o = msgp.AppendString(o, z.Players[za0001].Name)
		// string "ready"
		o = append(o, 0xa5, 0x72, 0x65, 0x61, 0x64, 0x79)
		o = msgp.AppendBool(o, z.Players[za0001].Ready)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PlayerInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "players":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Players")
				return
			}
			if cap(z.Players) >= int(zb0002) {
				z.Players = (z.Players)[:zb0002]
			} else {
				z.Players = make([]PlayerInfoPlayer, zb0002)
			}
			for za0001 := range z.Players {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Players", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Players", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "playerId":
						z.Players[za0001].Id, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Players", za0001, "Id")
							return
						}
					case "name":
						z.Players[za0001].Name, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Players", za0001, "Name")
							return
						}
					case "ready":
						z.Players[za0001].Ready, bts, err = msgp.ReadBoolBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Players", za0001, "Ready")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Players", za0001)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PlayerInfo) Msgsize() (s int) {
	s = 1 + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Players {
		s += 1 + 9 + msgp.StringPrefixSize + len(z.Players[za0001].Id) + 5 + msgp.StringPrefixSize + len(z.Players[za0001].Name) + 6 + msgp.BoolSize
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PlayerInfoPlayer) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "playerId":
			z.Id, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "ready":
			z.Ready, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Ready")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z PlayerInfoPlayer) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "playerId"
	err = en.Append(0x83, 0xa8, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "ready"
	err = en.Append(0xa5, 0x72, 0x65, 0x61, 0x64, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Ready)
	if err != nil {
		err = msgp.WrapError(err, "Ready")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z PlayerInfoPlayer) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "playerId"
	o = append(o, 0x83, 0xa8, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64)
	o = msgp.AppendString(o, z.Id)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "ready"
	o = append(o, 0xa5, 0x72, 0x65, 0x61, 0x64, 0x79)
	o = msgp.AppendBool(o, z.Ready)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PlayerInfoPlayer) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "playerId":
			z.Id, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "ready":
			z.Ready, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ready")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z PlayerInfoPlayer) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.Id) + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.BoolSize
	return
}
